import type { TailwindConfig } from '@react-email/components';

import { blue, crimson, gray, red } from '@radix-ui/colors';

export const config = {
  theme: {
    colors: {
      background: gray.gray1,
      foreground: gray.gray12,

      muted: {
        DEFAULT: gray.gray4,
        foreground: gray.gray11,
      },

      card: {
        DEFAULT: gray.gray1,
        foreground: gray.gray12,
      },

      popover: {
        DEFAULT: gray.gray1,
        foreground: gray.gray12,
      },

      input: gray.gray4,

      primary: {
        DEFAULT: crimson.crimson10,
        foreground: crimson.crimson1,
        1: crimson.crimson1,
        2: crimson.crimson2,
        3: crimson.crimson3,
        4: crimson.crimson4,
        5: crimson.crimson5,
        6: crimson.crimson6,
        7: crimson.crimson7,
        8: crimson.crimson8,
        9: crimson.crimson9,
        10: crimson.crimson10,
        11: crimson.crimson11,
        12: crimson.crimson12,
      },

      secondary: {
        DEFAULT: blue.blue10,
        foreground: blue.blue1,
        1: blue.blue1,
        2: blue.blue2,
        3: blue.blue3,
        4: blue.blue4,
        5: blue.blue5,
        6: blue.blue6,
        7: blue.blue7,
        8: blue.blue8,
        9: blue.blue9,
        10: blue.blue10,
        11: blue.blue11,
        12: blue.blue12,
      },

      accent: {
        DEFAULT: gray.gray4,
        foreground: gray.gray12,
      },

      destructive: {
        DEFAULT: red.red10,
        foreground: red.red1,
        1: red.red1,
        2: red.red2,
        3: red.red3,
        4: red.red4,
        5: red.red5,
        6: red.red6,
        7: red.red7,
        8: red.red8,
        9: red.red9,
        10: red.red10,
        11: red.red11,
        12: red.red12,
      },

      border: gray.gray4,
      ring: gray.gray4,
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: '2px',
      1: '4px',
      1.5: '6px',
      2: '8px',
      2.5: '10px',
      3: '12px',
      3.5: '14px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      9: '36px',
      10: '40px',
      11: '44px',
      12: '48px',
      14: '56px',
      16: '64px',
      20: '80px',
      24: '96px',
      28: '112px',
      32: '128px',
      36: '144px',
      40: '160px',
      44: '176px',
      48: '192px',
      52: '208px',
      56: '224px',
      60: '240px',
      64: '256px',
      72: '288px',
      80: '320px',
      96: '384px',
    },
    fontSize: {
      xs: ['12px', { lineHeight: '16px' }],
      sm: ['14px', { lineHeight: '20px' }],
      base: ['16px', { lineHeight: '24px' }],
      lg: ['18px', { lineHeight: '28px' }],
      xl: ['20px', { lineHeight: '28px' }],
      '2xl': ['24px', { lineHeight: '32px' }],
      '3xl': ['30px', { lineHeight: '36px' }],
      '4xl': ['36px', { lineHeight: '40px' }],
      '5xl': ['48px', { lineHeight: '1' }],
      '6xl': ['60px', { lineHeight: '1' }],
      '7xl': ['72px', { lineHeight: '1' }],
      '8xl': ['96px', { lineHeight: '1' }],
      '9xl': ['128px', { lineHeight: '1' }],
    },
    borderRadius: {
      none: '0',
      sm: '2px',
      DEFAULT: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
      '2xl': '16px',
      '3xl': '24px',
      full: '9999px',
    },
  },
} satisfies TailwindConfig;
