name: 'ðŸ˜ Create Neon DB Branch'
description: 'Steps to create or retrieve PR db branch from Neon'

inputs:
  project_id:
    description: 'The Neon project ID'
    required: true
  username:
    description: 'The Neon database username'
    required: true
  api_key:
    description: 'The Neon API key'
    required: true

runs:
  using: composite
  steps:
    - name: Get branch name
      id: branch_name
      uses: tj-actions/branch-names@v8

    - name: Create Neon Branch
      id: create-branch
      uses: neondatabase/create-branch-action@v4
      with:
        project_id: ${{ inputs.project_id }}
        branch_name: web/pr-${{ github.event.number}}-${{ steps.branch_name.outputs.current_branch }}
        username: ${{ inputs.username }}
        api_key: ${{ inputs.api_key }}

    - name: Set DATABASE_URL
      shell: bash
      run: |
        echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url }}?sslmode=require" >> $GITHUB_ENV
